[build-system]
requires = [
    "setuptools", 
    "numpy",
    "cython", 
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "starslugs"
version = "0.0.1"
dynamic = ["version"]
dependencies = [
    "numpy",
    "astropy",
    "scipy",
    "matplotlib",
    "deprecation",
    "pytest",
    "pandas",
    "astroquery"
]

[tool.setuptools.dynamic]
version = {attr = "starslugs.__version__"}

[tool.setuptools.packages]
find = {}